
---
- name: Deploy Flask App
  hosts: webservers
  become: yes

  tasks:
    - name: Pull Docker Image
      docker_image:
        name: elitesolutionsit/calculator-app:v1
        state: present

    - name: Start Docker Container
      docker_container:
        name: calculator-app
        image: elitesolutionsit/calculator-app:v1
        ports:
          - "3000:3000"
        state: started

