---
- hosts: webservers
  become: yes
  vars:
    docker_image: elitesolutionsit/react-shopping-app:v1
    container_name: react-shopping-app
    port_mapping: "80:80"
    dockerhub_username: elitesolutionsit
  
  tasks:
    - name: warn if access to the secret is denied
      debug: msg="{{ lookup('amazon.aws.aws_secret', 'secret-denied', on_denied='warn')}}"
    
    - name: lookup secretsmanager secret in the current region
    debug: msg="{{ lookup('amazon.aws.aws_secret', 'dev/docker-login-secret', bypath=true) }}"

    - name: Get Docker Hub password from AWS Secrets Manager
      aws_secretsmanager:
        region: us-east-1
        secret_id: "{{ lookup('amazon.aws.aws_secret', 'docker-login-secret') }}"

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ lookup('amazon.aws.aws_secret', 'docker-login-secret') }}"

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        pull: yes
        restart_policy: always
        ports:
          - "{{ port_mapping }}"
