---
- hosts: webservers
  become: yes
  vars:
    docker_image: elitesolutionsit/react-shopping-app
    container_name: react-shopping-app
    port_mapping: "80:80"
    dockerhub_username: elitesolutionsit
    dockerhub_secret: pafVbCat003B
    # dockerhub_secret_arn: arn:aws:secretsmanager:us-east-1:375866976303:secret:docker-login-secret-A3pSos
  
  tasks:
    - name: Get Docker Hub password from AWS Secrets Manager
      aws_secretsmanager:
        region: us-east-1
        secret_id: "{{ dockerhub_secret }}"
        register: dockerhub_secret

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_secret }}"

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        pull: yes
        restart_policy: always
        ports:
          - "{{ port_mapping }}"
