- hosts: webservers
  become: yes
  vars:
    docker_image: elitesolutionsit/react-shopping-app:v1
    container_name: react-shopping-app
    port_mapping:
      - "80:80"
    # dockerhub_username: elitesolutionsit
    dockerhub_username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
    dockerhub_password: "{{ lookup('jenkins', 'dockerhub-creds::password', 'username', lookup('env', 'DOCKERHUB_USERNAME')) }}"

  tasks:
    - name: Log in to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
        
    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        pull: yes
        restart_policy: always
        ports: "{{ port_mapping }}"
