
---
- name: Deploy Flask App
  hosts: webservers
  become: yes
  vars:
    mysql_root_password: "te$t%%$$"

  tasks:
    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Pull Docker Image
      docker_image:
        name: elitesolutionsit/flask-app:v1
        state: present

    - name: Start Docker Container
      docker_container:
        name: flask-app
        image: elitesolutionsit/flask-app:v1
        ports:
          - "5000:5000"
        state: started

    - name: Start MySQL container
      docker_container:
        name: mysql
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
        ports:
          - "3306:3306"
        restart_policy: always
        state: started
